// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXbkhPb_afwWNjx8aGTiU6kn3YET70Uvs',
    appId: '1:450093864363:web:ed8c5d488537ee92f7eeee',
    messagingSenderId: '450093864363',
    projectId: 'historymini-5ebea',
    authDomain: 'historymini-5ebea.firebaseapp.com',
    storageBucket: 'historymini-5ebea.firebasestorage.app',
    measurementId: 'G-YRNSM8QB50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9mJvPiW2PUqPbhh1vjCt16r6KEOB1hSU',
    appId: '1:450093864363:android:f87c472a98d77d4af7eeee',
    messagingSenderId: '450093864363',
    projectId: 'historymini-5ebea',
    storageBucket: 'historymini-5ebea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2J6VX1cXGejWoWDJhLj7HAMS9z-Bm-4Y',
    appId: '1:450093864363:ios:28bcd72880df6502f7eeee',
    messagingSenderId: '450093864363',
    projectId: 'historymini-5ebea',
    storageBucket: 'historymini-5ebea.firebasestorage.app',
    iosBundleId: 'com.example.historymini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2J6VX1cXGejWoWDJhLj7HAMS9z-Bm-4Y',
    appId: '1:450093864363:ios:28bcd72880df6502f7eeee',
    messagingSenderId: '450093864363',
    projectId: 'historymini-5ebea',
    storageBucket: 'historymini-5ebea.firebasestorage.app',
    iosBundleId: 'com.example.historymini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXbkhPb_afwWNjx8aGTiU6kn3YET70Uvs',
    appId: '1:450093864363:web:9625115255a4c1caf7eeee',
    messagingSenderId: '450093864363',
    projectId: 'historymini-5ebea',
    authDomain: 'historymini-5ebea.firebaseapp.com',
    storageBucket: 'historymini-5ebea.firebasestorage.app',
    measurementId: 'G-9EH6BKXM2L',
  );
}
